services:
  mysql:
    image: mysql:8.0 # 생성이미지:버전
    container_name: mysql # 생성 할 컨테이너 이름
    restart: always # 수동종료 전까지 항상 켜지도록 유지 (sleep 방지)
    ports:
      - "3306:3306" # 포트번호 host:docker 로컬 포트에 도커 포트를 마운트
    volumes:
      # 로컬저장경로:도커저장경로 / 컨테이너 종료 후에도 데이터를 로컬에 저장하여 유지 (로컬 경로변경 가능)
      - ./db/mysql/data:/var/lib/mysql
      # 로컬저장경로:도커저장경로 / 해당 경로에 작성된 DDL을 컨테이너 생성 시 자동실행 (.sql .sh 파일 실행) (로컬 경로변경 가능)
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    environment: #===== db 환경변수 =====#
      MYSQL_ROOT_PASSWORD: 1234 # root 계정 비밀번호 설정

  redis:
    image: redis:latest
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"